// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 761500761;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__decrypt_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "decrypt_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::types::BridgeDecryptRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::decrypt_file(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__embed_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "embed_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::types::BridgeEmbedRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::embed_file(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__encrypt_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encrypt_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::types::BridgeEncryptRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::encrypt_file(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__extract_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "extract_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::types::BridgeExtractRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::extract_file(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__generate_passphrase_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_passphrase",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::types::BridgePassphraseRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::generate_passphrase(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__generate_password_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_password",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_policy =
                <crate::api::types::BridgePasswordPolicy>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::generate_password(api_policy)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::types::BridgeDecryptRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_idPassword = <String>::sse_decode(deserializer);
        return crate::api::types::BridgeDecryptRequest {
            input_path: var_inputPath,
            output_path: var_outputPath,
            password: var_password,
            id_password: var_idPassword,
        };
    }
}

impl SseDecode for crate::api::types::BridgeEmbedRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_carrierPath = <String>::sse_decode(deserializer);
        let mut var_payloadPath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_mode = <crate::api::types::BridgeStegoMode>::sse_decode(deserializer);
        return crate::api::types::BridgeEmbedRequest {
            carrier_path: var_carrierPath,
            payload_path: var_payloadPath,
            output_path: var_outputPath,
            password: var_password,
            mode: var_mode,
        };
    }
}

impl SseDecode for crate::api::types::BridgeEncryptRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_idPassword = <String>::sse_decode(deserializer);
        let mut var_algorithm =
            <crate::api::types::BridgeEncryptionAlgorithm>::sse_decode(deserializer);
        return crate::api::types::BridgeEncryptRequest {
            input_path: var_inputPath,
            output_path: var_outputPath,
            password: var_password,
            id_password: var_idPassword,
            algorithm: var_algorithm,
        };
    }
}

impl SseDecode for crate::api::types::BridgeEncryptionAlgorithm {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::BridgeEncryptionAlgorithm::Aes256Gcm,
            _ => unreachable!("Invalid variant for BridgeEncryptionAlgorithm: {}", inner),
        };
    }
}

impl SseDecode for crate::api::types::BridgeExtractRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_carrierPath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_mode = <crate::api::types::BridgeStegoMode>::sse_decode(deserializer);
        return crate::api::types::BridgeExtractRequest {
            carrier_path: var_carrierPath,
            output_path: var_outputPath,
            password: var_password,
            mode: var_mode,
        };
    }
}

impl SseDecode for crate::api::types::BridgeOperationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_bytesProcessed = <u64>::sse_decode(deserializer);
        return crate::api::types::BridgeOperationResult {
            output_path: var_outputPath,
            bytes_processed: var_bytesProcessed,
        };
    }
}

impl SseDecode for crate::api::types::BridgePassphraseRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_wordCount = <usize>::sse_decode(deserializer);
        let mut var_separator = <String>::sse_decode(deserializer);
        let mut var_capitalizeWords = <bool>::sse_decode(deserializer);
        let mut var_appendNumber = <bool>::sse_decode(deserializer);
        return crate::api::types::BridgePassphraseRequest {
            word_count: var_wordCount,
            separator: var_separator,
            capitalize_words: var_capitalizeWords,
            append_number: var_appendNumber,
        };
    }
}

impl SseDecode for crate::api::types::BridgePasswordPolicy {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_length = <usize>::sse_decode(deserializer);
        let mut var_useLowercase = <bool>::sse_decode(deserializer);
        let mut var_useUppercase = <bool>::sse_decode(deserializer);
        let mut var_useDigits = <bool>::sse_decode(deserializer);
        let mut var_useSymbols = <bool>::sse_decode(deserializer);
        return crate::api::types::BridgePasswordPolicy {
            length: var_length,
            use_lowercase: var_useLowercase,
            use_uppercase: var_useUppercase,
            use_digits: var_useDigits,
            use_symbols: var_useSymbols,
        };
    }
}

impl SseDecode for crate::api::types::BridgeStegoMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::BridgeStegoMode::Append,
            _ => unreachable!("Invalid variant for BridgeStegoMode: {}", inner),
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__decrypt_file_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__embed_file_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__encrypt_file_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__extract_file_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__generate_passphrase_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__generate_password_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgeDecryptRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.id_password.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgeDecryptRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgeDecryptRequest>
    for crate::api::types::BridgeDecryptRequest
{
    fn into_into_dart(self) -> crate::api::types::BridgeDecryptRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgeEmbedRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.carrier_path.into_into_dart().into_dart(),
            self.payload_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgeEmbedRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgeEmbedRequest>
    for crate::api::types::BridgeEmbedRequest
{
    fn into_into_dart(self) -> crate::api::types::BridgeEmbedRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgeEncryptRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.id_password.into_into_dart().into_dart(),
            self.algorithm.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgeEncryptRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgeEncryptRequest>
    for crate::api::types::BridgeEncryptRequest
{
    fn into_into_dart(self) -> crate::api::types::BridgeEncryptRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgeEncryptionAlgorithm {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Aes256Gcm => 0.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgeEncryptionAlgorithm
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgeEncryptionAlgorithm>
    for crate::api::types::BridgeEncryptionAlgorithm
{
    fn into_into_dart(self) -> crate::api::types::BridgeEncryptionAlgorithm {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgeExtractRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.carrier_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgeExtractRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgeExtractRequest>
    for crate::api::types::BridgeExtractRequest
{
    fn into_into_dart(self) -> crate::api::types::BridgeExtractRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgeOperationResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_path.into_into_dart().into_dart(),
            self.bytes_processed.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgeOperationResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgeOperationResult>
    for crate::api::types::BridgeOperationResult
{
    fn into_into_dart(self) -> crate::api::types::BridgeOperationResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgePassphraseRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.word_count.into_into_dart().into_dart(),
            self.separator.into_into_dart().into_dart(),
            self.capitalize_words.into_into_dart().into_dart(),
            self.append_number.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgePassphraseRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgePassphraseRequest>
    for crate::api::types::BridgePassphraseRequest
{
    fn into_into_dart(self) -> crate::api::types::BridgePassphraseRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgePasswordPolicy {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.length.into_into_dart().into_dart(),
            self.use_lowercase.into_into_dart().into_dart(),
            self.use_uppercase.into_into_dart().into_dart(),
            self.use_digits.into_into_dart().into_dart(),
            self.use_symbols.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgePasswordPolicy
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgePasswordPolicy>
    for crate::api::types::BridgePasswordPolicy
{
    fn into_into_dart(self) -> crate::api::types::BridgePasswordPolicy {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BridgeStegoMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Append => 0.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BridgeStegoMode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BridgeStegoMode>
    for crate::api::types::BridgeStegoMode
{
    fn into_into_dart(self) -> crate::api::types::BridgeStegoMode {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::types::BridgeDecryptRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.output_path, serializer);
        <String>::sse_encode(self.password, serializer);
        <String>::sse_encode(self.id_password, serializer);
    }
}

impl SseEncode for crate::api::types::BridgeEmbedRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.carrier_path, serializer);
        <String>::sse_encode(self.payload_path, serializer);
        <String>::sse_encode(self.output_path, serializer);
        <String>::sse_encode(self.password, serializer);
        <crate::api::types::BridgeStegoMode>::sse_encode(self.mode, serializer);
    }
}

impl SseEncode for crate::api::types::BridgeEncryptRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.output_path, serializer);
        <String>::sse_encode(self.password, serializer);
        <String>::sse_encode(self.id_password, serializer);
        <crate::api::types::BridgeEncryptionAlgorithm>::sse_encode(self.algorithm, serializer);
    }
}

impl SseEncode for crate::api::types::BridgeEncryptionAlgorithm {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::BridgeEncryptionAlgorithm::Aes256Gcm => 0,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::types::BridgeExtractRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.carrier_path, serializer);
        <String>::sse_encode(self.output_path, serializer);
        <String>::sse_encode(self.password, serializer);
        <crate::api::types::BridgeStegoMode>::sse_encode(self.mode, serializer);
    }
}

impl SseEncode for crate::api::types::BridgeOperationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_path, serializer);
        <u64>::sse_encode(self.bytes_processed, serializer);
    }
}

impl SseEncode for crate::api::types::BridgePassphraseRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <usize>::sse_encode(self.word_count, serializer);
        <String>::sse_encode(self.separator, serializer);
        <bool>::sse_encode(self.capitalize_words, serializer);
        <bool>::sse_encode(self.append_number, serializer);
    }
}

impl SseEncode for crate::api::types::BridgePasswordPolicy {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <usize>::sse_encode(self.length, serializer);
        <bool>::sse_encode(self.use_lowercase, serializer);
        <bool>::sse_encode(self.use_uppercase, serializer);
        <bool>::sse_encode(self.use_digits, serializer);
        <bool>::sse_encode(self.use_symbols, serializer);
    }
}

impl SseEncode for crate::api::types::BridgeStegoMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::BridgeStegoMode::Append => 0,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
